export { Board } from './core/board.js';
export { Game } from './core/game.js';
export { createRandomizer, BagRandomizer, UniformRandomizer } from './core/randomizer.js';
export { tryRotate } from './core/srs.js';
export { Piece, Rotation, PIECE_COUNT, DEFAULT_CONFIG } from './core/types.js';
export type { GameConfig, GameSnapshot, Placement, FeatureVector, LockResult, Vec2 } from './core/types.js';
export { PIECE_CELLS, JLSTZ_KICKS, I_KICKS, getSpawnPosition } from './core/constants.js';
export { generatePlacements } from './ai/placement.js';
export { extractFeatures } from './ai/features.js';
export { evaluate } from './ai/evaluator.js';
export type { Weights } from './ai/evaluator.js';
export { BCTS_WEIGHTS, loadWeights, saveWeights } from './ai/weights.js';
export { greedySelect } from './ai/greedy.js';
export { beamSearch } from './ai/beam-search.js';
export type { BeamSearchConfig } from './ai/beam-search.js';
export { trainCrossEntropy } from './training/cross-entropy.js';
export type { CEConfig, CEResult } from './training/cross-entropy.js';
export { computeStats, formatStats } from './benchmark/stats.js';
export type { BenchmarkStats } from './benchmark/stats.js';
export { runBenchmark } from './benchmark/runner.js';
export type { BenchmarkConfig, BenchmarkResult } from './benchmark/runner.js';
